### ISSUE TITLE
Morning code review 1/09/2021

### ISSUE THREAD

**Issue by notlfish** [rotimiazeez/my-leaderboard#2]
For branch `project-setup`

**Comment by zainsadaqat** [comment]
# Hello @rotimiazeez 
Your project is looking great! 😃 
![](https://media4.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif)

**Comment by notlfish** [comment]
The project is looking great!
Remember to set the `dev` branch as the default one.
